server:
  port: 8201

spring:
  application:
    name: booking-service
  datasource:
    url: jdbc:mysql://localhost:3306/bookingdb?createDatabaseIfNotExist=true&useSSL=false
    username: root
    password: root

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

    spring:
  kafka:
    bootstrap-servers: localhost:9092

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
